name: Apex End to End Tests

on:

  workflow_dispatch:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'develop'
        type: string
      apexLsp:
        description: 'apexLsp.e2e.ts'
        required: false
        default: true
        type: boolean
      apexReplayDebugger:
        description: 'apexReplayDebugger.e2e.ts'
        required: false
        default: true
        type: boolean
      debugApexTests:
        description: 'debugApexTests.e2e.ts'
        required: false
        default: true
        type: boolean
      runApexTests:
        description: 'runApexTests.e2e.ts'
        required: false
        default: true
        type: boolean
      trailApexReplayDebugger:
        description: 'trailApexReplayDebugger.e2e.ts'
        required: false
        default: true
        type: boolean

  workflow_call:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'develop'
        type: string
      apexLsp:
        description: 'apexLsp.e2e.ts'
        required: false
        default: true
        type: boolean
      apexReplayDebugger:
        description: 'apexReplayDebugger.e2e.ts'
        required: false
        default: true
        type: boolean
      debugApexTests:
        description: 'debugApexTests.e2e.ts'
        required: false
        default: true
        type: boolean
      runApexTests:
        description: 'runApexTests.e2e.ts'
        required: false
        default: true
        type: boolean
      trailApexReplayDebugger:
        description: 'trailApexReplayDebugger.e2e.ts'
        required: false
        default: true
        type: boolean

jobs:

  run_apexLSP_if_selected:
    if: ${{ inputs.apexLsp }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'apexLsp.e2e.ts'

  run_apexReplayDebugger_if_selected:
    if: ${{ inputs.apexReplayDebugger }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'apexReplayDebugger.e2e.ts'

  run_debugApexTests_if_selected:
    if: ${{ inputs.debugApexTests }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'debugApexTests.e2e.ts'

  run_runApexTests_if_selected:
    if: ${{ inputs.runApexTests }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'runApexTests.e2e.ts'

  run_trailApexReplayDebugger_if_selected:
    if: ${{ inputs.trailApexReplayDebugger }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'trailApexReplayDebugger.e2e.ts'
