name: End to End Tests
on:
  workflow_dispatch:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'develop'
        type: string
      lspE2ETests:
        description: 'LSP e2e Tests'
        required: false
        default: true
        type: boolean
      apexE2ETests:
        description: 'Apex e2e Tests'
        required: false
        default: true
        type: boolean
      coreE2ETests:
        description: 'Core e2e Tests'
        required: false
        default: true
        type: boolean

jobs:

  run_LSP_E2E_tests_if_selected:
    if: ${{ inputs.lspE2ETests }}
    uses: ./.github/workflows/lspE2E.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}

  run_Apex_E2E_tests_if_selected:
    if: ${{ inputs.apexE2ETests }}
    uses: ./.github/workflows/apexE2E.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}

  run_Core_E2E_tests_if_selected:
    if: ${{ inputs.coreE2ETests }}
    uses: ./.github/workflows/coreE2E.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
