name: LSP End to End Tests
on:
  workflow_dispatch:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'develop'
        type: string
      auraLsp:
        description: 'auraLsp.e2e.ts'
        required: false
        default: true
        type: boolean
      lwcLsp:
        description: 'lwcLsp.e2e.ts'
        required: false
        default: true
        type: boolean
      visualforceLsp:
        description: 'visualforceLsp.e2e.ts'
        required: false
        default: true
        type: boolean
  workflow_call:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'develop'
        type: string
      auraLsp:
        description: 'auraLsp.e2e.ts'
        required: false
        default: true
        type: boolean
      lwcLsp:
        description: 'lwcLsp.e2e.ts'
        required: false
        default: true
        type: boolean
      visualforceLsp:
        description: 'visualforceLsp.e2e.ts'
        required: false
        default: true
        type: boolean

jobs:

  run_aura_LSP_if_selected:
    if: ${{ inputs.auraLsp }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'auraLsp.e2e.ts'

  run_lwc_LSP_if_selected:
    if: ${{ inputs.lwcLsp }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'lwcLsp.e2e.ts'

  run_visualforce_LSP_if_selected:
    if: ${{ inputs.visualforceLsp }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'visualforceLsp.e2e.ts'
