name: Test, Build, and Publish
on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:

jobs:
  build-and-test:
    uses: ./.github/workflows/buildAndTest.yml
    with: 
      branch: 'main'
  publish:
    needs: [build-and-test]
    uses: ./.github/workflows/publish.yml
  
